CREATE TABLE "service_translations" (
	"service_id" uuid NOT NULL,
	"locale" varchar(8) NOT NULL,
	"name" varchar(200) NOT NULL,
	"summary" varchar(300),
	"description" text,
	"purpose" text,
	"requirements" text,
	"location" varchar(300),
	"availability" varchar(300),
	CONSTRAINT "service_translations_service_id_locale_pk" PRIMARY KEY("service_id","locale")
);
--> statement-breakpoint
CREATE TABLE "services" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"slug" varchar(120) NOT NULL,
	"category" varchar(16) NOT NULL,
	"status" varchar(16) DEFAULT 'draft' NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"price_cents" integer,
	"price_from" boolean DEFAULT false NOT NULL,
	"duration_minutes" integer,
	"modes" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"booking_open" boolean DEFAULT true NOT NULL,
	"image_url" varchar(500),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "services_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
ALTER TABLE "service_translations" ADD CONSTRAINT "service_translations_service_id_services_id_fk" FOREIGN KEY ("service_id") REFERENCES "public"."services"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
-- Starts the list with the services the site already showed; each can be edited or removed in the admin.
WITH added AS (
 INSERT INTO "services" ("slug", "category", "status", "sort_order", "modes") VALUES
  ('kundali', 'astrology', 'published', 10, '["in_person", "phone", "zoom"]'::jsonb),
  ('kundali-analysis', 'astrology', 'published', 20, '["in_person", "phone", "zoom"]'::jsonb),
  ('marriage-compatibility', 'astrology', 'published', 30, '["in_person", "phone", "zoom"]'::jsonb),
  ('career-astrology', 'astrology', 'published', 40, '["in_person", "phone", "zoom"]'::jsonb),
  ('financial-astrology', 'astrology', 'published', 50, '["in_person", "phone", "zoom"]'::jsonb),
  ('graha-dasha', 'astrology', 'published', 60, '["in_person", "phone", "zoom"]'::jsonb),
  ('navagraha-consultation', 'astrology', 'published', 70, '["in_person", "phone", "zoom"]'::jsonb),
  ('vastu', 'astrology', 'published', 80, '["in_person", "home_visit", "zoom"]'::jsonb),
  ('muhurat', 'astrology', 'published', 90, '["in_person", "phone", "zoom"]'::jsonb),
  ('prashna-kundali', 'astrology', 'published', 100, '["in_person", "phone", "zoom"]'::jsonb),
  ('name-analysis', 'astrology', 'published', 110, '["in_person", "phone", "zoom"]'::jsonb),
  ('numerology', 'astrology', 'published', 120, '["in_person", "phone", "zoom"]'::jsonb),
  ('rudrabhishek', 'puja', 'published', 10, '["in_person", "home_visit"]'::jsonb),
  ('satyanarayan-puja', 'puja', 'published', 20, '["in_person", "home_visit"]'::jsonb),
  ('navagraha-puja', 'puja', 'published', 30, '["in_person", "home_visit"]'::jsonb),
  ('graha-shanti', 'puja', 'published', 40, '["in_person", "home_visit"]'::jsonb),
  ('lakshmi-puja', 'puja', 'published', 50, '["in_person", "home_visit"]'::jsonb),
  ('griha-pravesh', 'puja', 'published', 60, '["home_visit"]'::jsonb),
  ('havan', 'puja', 'published', 70, '["in_person", "home_visit"]'::jsonb),
  ('marriage-rituals', 'puja', 'published', 80, '["in_person", "home_visit"]'::jsonb),
  ('bratabandha', 'puja', 'published', 90, '["in_person", "home_visit"]'::jsonb),
  ('shraddha', 'puja', 'published', 100, '["in_person", "home_visit"]'::jsonb),
  ('custom-puja', 'puja', 'published', 110, '["in_person", "home_visit"]'::jsonb)
 ON CONFLICT ("slug") DO NOTHING
 RETURNING "id", "slug"
)
INSERT INTO "service_translations" ("service_id", "locale", "name", "summary")
SELECT added."id", v."locale", v."name", v."summary" FROM added JOIN (VALUES
  ('kundali', 'en', 'Birth Chart / Kundali', 'Your Vedic birth chart, prepared from your date, time and place of birth.'),
  ('kundali', 'ne', 'जन्मकुण्डली', NULL),
  ('kundali', 'sa', 'जन्मकुण्डली', NULL),
  ('kundali-analysis', 'en', 'Kundali Analysis', 'A detailed reading of your birth chart: the planets, houses and yogas, and what they mean for your life.'),
  ('kundali-analysis', 'ne', 'कुण्डली विश्लेषण', NULL),
  ('kundali-analysis', 'sa', 'कुण्डलीविश्लेषणम्', NULL),
  ('marriage-compatibility', 'en', 'Marriage Compatibility', 'Kundali matching (Guna Milan) for couples planning to marry, with guidance on any doshas.'),
  ('marriage-compatibility', 'ne', 'विवाह गुण मिलान', NULL),
  ('marriage-compatibility', 'sa', 'विवाहगुणमेलनम्', NULL),
  ('career-astrology', 'en', 'Career Astrology', 'Guidance on career direction, job changes and good timing, based on your chart.'),
  ('career-astrology', 'ne', 'करियर ज्योतिष', NULL),
  ('career-astrology', 'sa', 'वृत्तिज्योतिषम्', NULL),
  ('financial-astrology', 'en', 'Financial Astrology', 'Insight into wealth, business and financial timing from your birth chart.'),
  ('financial-astrology', 'ne', 'आर्थिक ज्योतिष', NULL),
  ('financial-astrology', 'sa', 'आर्थिकज्योतिषम्', NULL),
  ('graha-dasha', 'en', 'Graha Dasha Analysis', 'Understanding your current and coming planetary periods (Mahadasha and Antardasha).'),
  ('graha-dasha', 'ne', 'ग्रह दशा विश्लेषण', NULL),
  ('graha-dasha', 'sa', 'ग्रहदशाविश्लेषणम्', NULL),
  ('navagraha-consultation', 'en', 'Navagraha Consultation', 'How the nine planets influence your chart, and remedies to bring them into balance.'),
  ('navagraha-consultation', 'ne', 'नवग्रह परामर्श', NULL),
  ('navagraha-consultation', 'sa', 'नवग्रहपरामर्शः', NULL),
  ('vastu', 'en', 'Vastu Consultation', 'Vastu Shastra guidance for your home, office or new property.'),
  ('vastu', 'ne', 'वास्तु परामर्श', NULL),
  ('vastu', 'sa', 'वास्तुपरामर्शः', NULL),
  ('muhurat', 'en', 'Muhurat', 'An auspicious date and time for a wedding, griha pravesh, business opening or other occasion.'),
  ('muhurat', 'ne', 'मुहूर्त', NULL),
  ('muhurat', 'sa', 'मुहूर्तम्', NULL),
  ('prashna-kundali', 'en', 'Prashna Kundali', 'An answer to one specific question, using a chart cast for the moment you ask it.'),
  ('prashna-kundali', 'ne', 'प्रश्न कुण्डली', NULL),
  ('prashna-kundali', 'sa', 'प्रश्नकुण्डली', NULL),
  ('name-analysis', 'en', 'Name Analysis', 'Choosing or reviewing a name in harmony with the birth nakshatra.'),
  ('name-analysis', 'ne', 'नाम विश्लेषण', NULL),
  ('name-analysis', 'sa', 'नामविश्लेषणम्', NULL),
  ('numerology', 'en', 'Numerology', 'What the numbers in your birth date and name reveal.'),
  ('numerology', 'ne', 'अंक ज्योतिष', NULL),
  ('numerology', 'sa', 'अङ्कज्योतिषम्', NULL),
  ('rudrabhishek', 'en', 'Rudrabhishek', 'Sacred abhishek of Lord Shiva with Vedic mantras, for peace, health and removing obstacles.'),
  ('rudrabhishek', 'ne', 'रुद्राभिषेक', NULL),
  ('rudrabhishek', 'sa', 'रुद्राभिषेकः', NULL),
  ('satyanarayan-puja', 'en', 'Satyanarayan Puja', 'Satyanarayan Katha and puja for gratitude, blessings and new beginnings.'),
  ('satyanarayan-puja', 'ne', 'सत्यनारायण पूजा', NULL),
  ('satyanarayan-puja', 'sa', 'सत्यनारायणपूजा', NULL),
  ('navagraha-puja', 'en', 'Navagraha Puja', 'Worship of the nine planets to ease difficult planetary influences.'),
  ('navagraha-puja', 'ne', 'नवग्रह पूजा', NULL),
  ('navagraha-puja', 'sa', 'नवग्रहपूजा', NULL),
  ('graha-shanti', 'en', 'Graha Shanti', 'A shanti puja to calm one troubling planet in your chart.'),
  ('graha-shanti', 'ne', 'ग्रह शान्ति', NULL),
  ('graha-shanti', 'sa', 'ग्रहशान्तिः', NULL),
  ('lakshmi-puja', 'en', 'Lakshmi Puja', 'Puja to Goddess Lakshmi for prosperity, at Tihar (Diwali) or for a new business.'),
  ('lakshmi-puja', 'ne', 'लक्ष्मी पूजा', NULL),
  ('lakshmi-puja', 'sa', 'लक्ष्मीपूजा', NULL),
  ('griha-pravesh', 'en', 'Griha Pravesh', 'Housewarming puja to bless a new home before you move in.'),
  ('griha-pravesh', 'ne', 'गृह प्रवेश', NULL),
  ('griha-pravesh', 'sa', 'गृहप्रवेशः', NULL),
  ('havan', 'en', 'Havan', 'A sacred fire ceremony with Vedic mantras, for purification and blessings.'),
  ('havan', 'ne', 'हवन', NULL),
  ('havan', 'sa', 'हवनम्', NULL),
  ('marriage-rituals', 'en', 'Marriage Rituals', 'Vedic wedding ceremonies and the rituals before and after the wedding.'),
  ('marriage-rituals', 'ne', 'विवाह संस्कार', NULL),
  ('marriage-rituals', 'sa', 'विवाहसंस्कारः', NULL),
  ('bratabandha', 'en', 'Bratabandha', 'The sacred thread ceremony (Upanayana).'),
  ('bratabandha', 'ne', 'व्रतबन्ध', NULL),
  ('bratabandha', 'sa', 'व्रतबन्धः', NULL),
  ('shraddha', 'en', 'Shraddha', 'Rituals to honor departed ancestors and offer them peace.'),
  ('shraddha', 'ne', 'श्राद्ध', NULL),
  ('shraddha', 'sa', 'श्राद्धम्', NULL),
  ('custom-puja', 'en', 'Other Custom Puja', 'Any other puja or ritual you need. Tell us what you have in mind.'),
  ('custom-puja', 'ne', 'अन्य विशेष पूजा', NULL),
  ('custom-puja', 'sa', 'अन्या विशेषपूजा', NULL)
) AS v("slug", "locale", "name", "summary") ON v."slug" = added."slug";
